services:
  mysql:
    image: mysql:8.0.39
    container_name: mysql3306
    hostname: database
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_COMMON_USER}
      MYSQL_PASSWORD: ${MYSQL_COMMON_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_EXPOSE_PORT}:3306
    volumes:
      - ${MYSQL_INIT}:/docker-entrypoint-initdb.d
      - ${MYSQL_STORE}:/var/lib/mysql
    restart: always
  redis:
    image: redis:7.4.0
    container_name: redis
    ports:
      - ${REDIS_PORT}:6379
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - ${MQ_CONTROLLER_EXPOSE_PORT}:15672
      - ${MQ_EXPOSE_PORT}:5672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
