server:
  port: 8080
springdoc:
  paths-to-match: /**
  paths-to-exclude: /error/**
  swagger-ui:
    operations-sorter: alpha
    path: /swagger-ui.html
spring:
  mail:
    host: ${MAIL_HOST:smtp.163.com}
    username: ${MAIL_USERNAME:15340791287@163.com}
    password: ${MAIL_PASSWORD:PMFQPODUGZIJJZBT}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB}:db
    username: ${MYSQL_ROOT_USER:root}
    password: ${MYSQL_ROOT_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    addresses: ${RABBITMQ_HOST:localhost}
    username: ${RABBITMQ_USER:root}
    password: ${RABBITMQ_PASS:root}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST}:/
  security:
    jwt:
      key: ${SECURITY_JWT_KEY:kkkeeeyyy}
      expire: 72
      limit:
        base: 10
        upgrade: 300
        frequency: 30
    filter:
      order: -100
  web:
    verify:
      mail-limit: 60
    flow:
      period: 5
      limit: 100
      block: 30
    cors:
      origin: ${ALLOWED_ORIGINS}:'*'
      credentials: false
      methods: ${ALLOWED_METHODS}:'*'
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: tb_